# Generated by Django 4.2.9 on 2024-01-16 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('client_short', models.CharField(max_length=10)),
                ('role_type', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_onboarded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Site_Configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('site_name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=40)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind')], default='Solar', max_length=12)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('log_ts', models.DateTimeField(auto_now_add=True)),
                ('variables', models.CharField(max_length=256)),
                ('ac_dc', models.FloatField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='register_app.clients', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_status', models.BooleanField(choices=[('ACTIVE', True), ('INACTIVE', False)], default=False)),
                ('verified', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED')),
                ('site_v_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_v_id', to='register_app.site_configs', to_field='site_id')),
            ],
        ),
    ]
