# Generated by Django 4.2.9 on 2024-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_short',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
