# Generated by Django 4.2.9 on 2024-01-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_alter_clients_client_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='plans',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic')], default='Basic', max_length=40),
        ),
    ]
