# Generated by Django 4.2.9 on 2024-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0004_site_configs_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_configs',
            name='ac_dc',
            field=models.FloatField(blank=True),
        ),
    ]
