# Generated by Django 4.2.9 on 2024-01-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0006_alter_site_configs_ac_dc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteverification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
